/**
 * Per-field descriptions for OpenAPI schemas.
 *
 * Keys are resource names (matching the keys in `resources.ts`) → camelCase
 * field name → either a plain description string OR an object with
 * `{ description, enum }` for fields that should be emitted as an OpenAPI
 * enum (e.g. `segment` with a finite set of values from the DB).
 *
 * Keep descriptions short and factual — think "docstring you'd read in a
 * tooltip", not "essay". For fields backed by a real enum in the data,
 * prefer the object form — it lets codegen clients generate proper enum
 * types instead of plain strings.
 */

export interface FieldDescriptionWithEnum {
  description: string;
  /** Complete list of allowed values, sourced from the live DB. */
  enum: string[];
}

export type FieldDescription = string | FieldDescriptionWithEnum;
export type FieldDescriptionMap = Record<string, FieldDescription>;

export const SHARED_DESCRIPTIONS: FieldDescriptionMap = {
  id: "Stable internal identifier",
  slug: "URL-safe unique identifier used in API paths",
  name: "Display name",
  source: "Upstream data source identifier (e.g. EIA, HIFLD, OSM)",
  sourceUrl: "Canonical source URL (filing PDF, dataset download, etc.)",
  createdAt: "When this record was first ingested into CommonGrid",
  updatedAt: "When this record was last modified",
  deletedAt: "Soft-delete timestamp (null for active records)",
  version: "Monotonic version counter incremented on every edit",
};

export const DESCRIPTIONS: Record<string, FieldDescriptionMap> = {
  utility: {
    ...SHARED_DESCRIPTIONS,
    eiaName: "Utility name as reported on EIA Form 861",
    shortName: "Short / display name variant",
    logo: "URL to the utility's logo",
    website: "Primary utility website",
    eiaId: "EIA utility identifier",
    segment: {
      description:
        "Ownership / structural category of the utility. Sourced from EIA Form 861 filings plus manual review.",
      // Pulled from `SELECT DISTINCT segment FROM utilities WHERE deleted_at IS NULL`.
      // Keep alphabetized. Re-run the query and update this list whenever a new
      // segment is introduced (rare; a PR to this file + regenerate the spec).
      enum: [
        "COMMUNITY_CHOICE_AGGREGATOR",
        "DISTRIBUTION_COOPERATIVE",
        "GENERATION_AND_TRANSMISSION",
        "INVESTOR_OWNED_UTILITY",
        "MUNICIPAL_UTILITY",
        "POLITICAL_SUBDIVISION",
        "TRANSMISSION_OPERATOR",
      ],
    },
    status: {
      description: "Operational status of the utility.",
      // Pulled from `SELECT DISTINCT status FROM utilities WHERE deleted_at IS NULL`.
      enum: ["ACTIVE", "DEFUNCT", "MERGED"],
    },
    customerCount: "Number of retail customers served (EIA-861)",
    peakDemandMw: "Summer peak demand in megawatts",
    winterPeakDemandMw: "Winter peak demand in megawatts",
    totalRevenueDollars: "Total annual revenue in US dollars",
    totalSalesMwh: "Total annual retail sales in MWh",
    baCode: "Balancing authority code (EIA-861)",
    nercRegion: "NERC reliability region",
    hasGeneration: "Whether the utility owns generation assets",
    hasTransmission: "Whether the utility owns transmission assets",
    hasDistribution: "Whether the utility owns distribution assets",
    amiMeterCount: "Number of advanced (AMI) meters deployed",
    totalMeterCount: "Total meter count (AMI + traditional)",
    jurisdiction: "Comma-separated state codes the utility operates in",
    isoId: "FK to the ISO this utility operates under, if any",
    rtoId: "FK to the RTO this utility operates under, if any",
    balancingAuthorityId: "FK to the primary balancing authority",
    generationProviderId: "FK to the utility that supplies generation",
    transmissionProviderId: "FK to the utility that supplies transmission",
    parentId: "FK to parent utility (holding company)",
    successorId: "FK to successor utility (post-merger)",
    serviceTerritoryId: "FK to the region describing the utility's service territory",
    domains: "Email / web domains associated with this utility (e.g. ['duke-energy.com']). Useful for CRM email scoping, communication tracking, and partner integrations. Backfilled from website + NRECA/EIA-861 where available; editable via the community contribution flow.",
  },
  powerPlant: {
    ...SHARED_DESCRIPTIONS,
    plantCode: "EIA plant code",
    utilityId: "FK to the operating utility",
    utilityName: "Operator name as reported to EIA",
    balancingAuthorityId: "FK to the balancing authority",
    baCode: "Balancing authority code",
    state: "Two-letter US state code",
    county: "County name",
    latitude: "WGS84 latitude",
    longitude: "WGS84 longitude",
    nercRegion: "NERC reliability region",
    sector: "EIA sector (electric utility, IPP, commercial, etc.)",
    primaryFuel: "Primary fuel code (EIA)",
    fuelCategory: "Normalized fuel category (solar, wind, gas, coal, etc.)",
    technologies: "Array of generator technology codes",
    energySources: "Array of energy source codes",
    totalCapacityMw: "Total nameplate capacity in megawatts",
    generatorCount: "Number of generators at the plant",
    operatingYear: "Earliest generator operating year",
    gridVoltageKv: "Grid interconnection voltage in kV",
    status: "One of: operable, proposed",
    proposedCapacityMw: "Proposed capacity in megawatts (for proposed plants)",
    proposedOnlineYear: "Expected online year (for proposed plants)",
  },
  evStation: {
    ...SHARED_DESCRIPTIONS,
    stationName: "Display name of the station",
    streetAddress: "Street address",
    city: "City",
    state: "Two-letter US state code",
    zip: "ZIP code",
    latitude: "WGS84 latitude",
    longitude: "WGS84 longitude",
    evNetwork: "Charging network (e.g. Tesla, ChargePoint, EVgo)",
    evLevel1EvseNum: "Number of Level 1 EVSE ports",
    evLevel2EvseNum: "Number of Level 2 EVSE ports",
    evDcFastNum: "Number of DC fast chargers",
    evConnectorTypes: "Array of connector types (J1772, CCS, CHAdeMO, TESLA)",
    accessCode: "One of: public, private",
    statusCode: "One of: E (available), P (planned), T (temporarily unavailable)",
    openDate: "Date the station opened (YYYY-MM-DD)",
    facilityType: "Facility type from AFDC",
    ownerTypeCode: "Owner type code from AFDC",
    evPricing: "Pricing information (free text)",
  },
  program: {
    ...SHARED_DESCRIPTIONS,
    description: "Full program description",
    organizations: "Array of {entityId, role} objects describing involved organizations",
    assetTypes: "Array of asset types (e.g. battery, thermostat, water-heater)",
    marketSegments: "Array of market segments (residential, C&I, etc.)",
    participationModels: "Array of participation model codes",
    incentiveStructures: "Array of incentive structure codes",
    gridServices: "Array of grid services the program provides",
    regions: "Array of region IDs covered",
    compensationTiers: "Array of compensation tiers",
    capacityTarget: "Target capacity in MW",
    maxEnrollments: "Max enrollment count, if any",
    programSeason: "Season object with startMonth, endMonth",
    launchedAt: "Launch date (YYYY-MM-DD)",
    enrollmentOpens: "Enrollment window open date",
    enrollmentCloses: "Enrollment window close date",
    endsAt: "Program end date",
    status: "Program status",
    programWebsite: "Program home page URL",
    faqUrl: "FAQ URL",
    termsUrl: "Terms & conditions URL",
    contactUrl: "Contact URL",
    variants: "Array of program variants",
  },
  pricingNode: {
    ...SHARED_DESCRIPTIONS,
    iso: "ISO/RTO identifier (CAISO, PJM, ERCOT, MISO, NYISO, ISONE, SPP)",
    nodeType: "Pricing node type (hub, gen, load, zone, etc.)",
    latitude: "WGS84 latitude",
    longitude: "WGS84 longitude",
    zone: "Pricing zone",
    state: "Two-letter US state code",
    voltageKv: "Voltage in kV",
    eiaPlantCode: "EIA plant code, for nodes mapped to a generator",
  },
  substation: {
    ...SHARED_DESCRIPTIONS,
    ownerName: "Owner name (free-text)",
    ownerUtilityId: "FK to the owning utility, if matched",
    state: "Two-letter US state code",
    county: "County name",
    latitude: "WGS84 latitude",
    longitude: "WGS84 longitude",
    minVoltageKv: "Minimum voltage in kV",
    maxVoltageKv: "Maximum voltage in kV",
    substationType: "One of: transmission, distribution, hybrid, unknown",
    status: "One of: in_service, out_of_service, planned, retired, unknown",
    eiaId: "EIA substation identifier",
    osmId: "OpenStreetMap element id (e.g. node/123, way/456)",
    hifldLegacyId: "Legacy HIFLD substation id",
  },
  transmissionLine: {
    ...SHARED_DESCRIPTIONS,
    objectId: "HIFLD object identifier",
    type: "Line type (overhead, underground, etc.)",
    status: "Operational status",
    owner: "Owner name",
    voltage: "Nominal voltage in kV (may be 0 for unknown)",
    voltClass: "HIFLD voltage class text",
    voltageClass: "Normalized voltage class (UNDER_100, 100_200, 345, 500, 735_AND_ABOVE, DC, NOT_AVAILABLE)",
    sub1: "First substation endpoint name",
    sub2: "Second substation endpoint name",
    lengthMiles: "Line length in miles",
    naicsCode: "NAICS industry code",
  },
  balancingAuthority: {
    ...SHARED_DESCRIPTIONS,
    shortName: "Short name / abbreviation",
    logo: "Logo URL",
    eiaCode: "EIA balancing authority code",
    eiaId: "EIA identifier",
    website: "Primary website",
    states: "Array of two-letter US state codes covered",
    isoId: "FK to the parent ISO, if any",
    regionId: "FK to the region this BA sits inside",
  },
  iso: {
    ...SHARED_DESCRIPTIONS,
    shortName: "Short name (e.g. CAISO, PJM)",
    logo: "Logo URL",
    website: "Primary website",
    states: "Array of two-letter US state codes covered",
    regionId: "FK to the parent region",
  },
  rto: {
    ...SHARED_DESCRIPTIONS,
    shortName: "Short name / abbreviation",
    logo: "Logo URL",
    website: "Primary website",
    states: "Array of two-letter US state codes covered",
    regionId: "FK to the parent region",
  },
  region: {
    ...SHARED_DESCRIPTIONS,
    type: "Region type (state, county, iso, rto, ba, utility-service-territory, cca, etc.)",
    eiaId: "EIA identifier, if applicable",
    state: "Two-letter US state code, if applicable",
    customers: "Customer count associated with this region, if reported",
    sourceDate: "Source filing date (YYYY-MM-DD)",
  },
  territory: {
    id: "Matches the region id this territory is the geometry for",
    regionId: "FK to the region",
    areaSqKm: "Area in square kilometers (precomputed)",
    vertexCount: "Vertex count (precomputed, for perf monitoring)",
    source: "Upstream source of the boundary geometry",
    sourceUrl: "Canonical source URL",
    createdAt: "When the geometry was first ingested",
    updatedAt: "When the geometry was last modified",
    deletedAt: "Soft-delete timestamp",
  },
};
