#!/usr/bin/env tsx

/**
 * Seed community_editable_fields table
 *
 * Populates field definitions for all entity types: utilities, power-plants,
 * ev-stations, pricing-nodes, programs.
 *
 * Usage:
 *   export DATABASE_URL=$(HOME=/var/tmp/op-agent op read "op://Fleet Secrets/CommonGrid Neon DB/password")
 *   tsx scripts/seed-editable-fields.ts
 */

import { sql } from "drizzle-orm";
import { db } from "../lib/db/client";
import { communityEditableFields } from "../lib/db/schema/community-editable-fields";
import { AssetType, GridService, IncentiveStructure, MarketSegment, ParticipationModel } from "../types/programs";

interface EditableFieldDefinition {
  entityType: string;
  fieldName: string;
  fieldType: "text" | "integer" | "float" | "boolean" | "enum" | "multi_enum" | "url";
  isCritical: boolean;
  displayName: string;
  validationRules?: Record<string, unknown>;
  section?: string;
  precision?: number;
  unit?: string;
  minValue?: number;
  maxValue?: number;
  enumSource?: string;
}

const fields: EditableFieldDefinition[] = [
  // === UTILITIES ===
  {
    entityType: "utility",
    fieldName: "name",
    fieldType: "text",
    isCritical: true,
    displayName: "Name",
    section: "basic",
    validationRules: { minLength: 2, maxLength: 255 },
  },
  {
    entityType: "utility",
    fieldName: "short_name",
    fieldType: "text",
    isCritical: false,
    displayName: "Short Name",
    section: "basic",
    validationRules: { maxLength: 100 },
  },
  {
    entityType: "utility",
    fieldName: "website",
    fieldType: "url",
    isCritical: false,
    displayName: "Website",
    section: "contact",
  },
  {
    entityType: "utility",
    fieldName: "customer_count",
    fieldType: "integer",
    isCritical: true,
    displayName: "Customer Count",
    section: "metrics",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "utility",
    fieldName: "peak_demand_mw",
    fieldType: "float",
    isCritical: true,
    displayName: "Peak Demand",
    section: "metrics",
    precision: 2,
    unit: "MW",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "utility",
    fieldName: "winter_peak_demand_mw",
    fieldType: "float",
    isCritical: true,
    displayName: "Winter Peak Demand",
    section: "metrics",
    precision: 2,
    unit: "MW",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "utility",
    fieldName: "total_revenue_dollars",
    fieldType: "float",
    isCritical: true,
    displayName: "Total Revenue",
    section: "financials",
    precision: 2,
    unit: "USD",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "utility",
    fieldName: "total_sales_mwh",
    fieldType: "float",
    isCritical: true,
    displayName: "Total Sales",
    section: "metrics",
    precision: 2,
    unit: "MWh",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "utility",
    fieldName: "ami_meter_count",
    fieldType: "integer",
    isCritical: false,
    displayName: "AMI Meter Count",
    section: "infrastructure",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "utility",
    fieldName: "total_meter_count",
    fieldType: "integer",
    isCritical: false,
    displayName: "Total Meter Count",
    section: "infrastructure",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "utility",
    fieldName: "jurisdiction",
    fieldType: "text",
    isCritical: false,
    displayName: "Jurisdiction",
    section: "regulatory",
  },
  {
    entityType: "utility",
    fieldName: "segment",
    fieldType: "enum",
    isCritical: true,
    displayName: "Segment",
    section: "basic",
    enumSource: "utility_segment",
    validationRules: {
      enum: [
        "INVESTOR_OWNED_UTILITY",
        "DISTRIBUTION_COOPERATIVE",
        "GENERATION_AND_TRANSMISSION",
        "MUNICIPAL_UTILITY",
        "COMMUNITY_CHOICE_AGGREGATOR",
        "POLITICAL_SUBDIVISION",
        "TRANSMISSION_OPERATOR",
        "JOINT_ACTION_AGENCY",
        "FEDERAL",
      ],
    },
  },
  {
    entityType: "utility",
    fieldName: "status",
    fieldType: "enum",
    isCritical: true,
    displayName: "Status",
    section: "basic",
    enumSource: "utility_status",
    validationRules: {
      enum: ["ACTIVE", "MERGED", "ACQUIRED", "DEFUNCT", "PENDING"],
    },
  },
  {
    entityType: "utility",
    fieldName: "eia_id",
    fieldType: "integer",
    isCritical: true,
    displayName: "EIA ID",
    section: "basic",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "utility",
    fieldName: "nerc_region",
    fieldType: "enum",
    isCritical: false,
    displayName: "NERC Region",
    section: "regulatory",
    validationRules: {
      enum: [
        "BASN",
        "CALN",
        "CALS",
        "DSW",
        "ASCC",
        "ISNE",
        "MISO",
        "NVDA",
        "NYCA",
        "ERCOT",
        "FRCC",
        "HICC",
        "MRO",
        "NPCC",
        "RFC",
        "SERC",
        "SPP",
        "TRE",
        "WECC",
      ],
    },
  },

  // === POWER PLANTS ===
  {
    entityType: "power_plant",
    fieldName: "name",
    fieldType: "text",
    isCritical: true,
    displayName: "Plant Name",
    section: "basic",
    validationRules: { minLength: 2, maxLength: 255 },
  },
  {
    entityType: "power_plant",
    fieldName: "state",
    fieldType: "enum",
    isCritical: true,
    displayName: "State",
    section: "location",
    enumSource: "us_state",
  },
  {
    entityType: "power_plant",
    fieldName: "county",
    fieldType: "text",
    isCritical: false,
    displayName: "County",
    section: "location",
  },
  {
    entityType: "power_plant",
    fieldName: "latitude",
    fieldType: "float",
    isCritical: true,
    displayName: "Latitude",
    section: "location",
    precision: 6,
    minValue: -90,
    maxValue: 90,
    validationRules: { min: -90, max: 90 },
  },
  {
    entityType: "power_plant",
    fieldName: "longitude",
    fieldType: "float",
    isCritical: true,
    displayName: "Longitude",
    section: "location",
    precision: 6,
    minValue: -180,
    maxValue: 180,
    validationRules: { min: -180, max: 180 },
  },
  {
    entityType: "power_plant",
    fieldName: "total_capacity_mw",
    fieldType: "float",
    isCritical: true,
    displayName: "Total Capacity",
    section: "technical",
    precision: 2,
    unit: "MW",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "power_plant",
    fieldName: "primary_fuel",
    fieldType: "text",
    isCritical: false,
    displayName: "Primary Fuel",
    section: "technical",
  },
  {
    entityType: "power_plant",
    fieldName: "operating_year",
    fieldType: "integer",
    isCritical: false,
    displayName: "Operating Year",
    section: "technical",
    minValue: 1800,
    maxValue: 2100,
    validationRules: { min: 1800, max: 2100 },
  },
  {
    entityType: "power_plant",
    fieldName: "grid_voltage_kv",
    fieldType: "float",
    isCritical: false,
    displayName: "Grid Voltage",
    section: "technical",
    precision: 2,
    unit: "kV",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "power_plant",
    fieldName: "status",
    fieldType: "enum",
    isCritical: true,
    displayName: "Status",
    section: "basic",
    enumSource: "power_plant_status",
    validationRules: { enum: ["operable", "proposed", "retired"] },
  },
  {
    entityType: "power_plant",
    fieldName: "proposed_capacity_mw",
    fieldType: "float",
    isCritical: false,
    displayName: "Proposed Capacity",
    section: "technical",
    precision: 2,
    unit: "MW",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "power_plant",
    fieldName: "proposed_online_year",
    fieldType: "integer",
    isCritical: false,
    displayName: "Proposed Online Year",
    section: "technical",
    minValue: 2020,
    maxValue: 2100,
    validationRules: { min: 2020, max: 2100 },
  },

  // === EV STATIONS ===
  {
    entityType: "ev_station",
    fieldName: "station_name",
    fieldType: "text",
    isCritical: false,
    displayName: "Station Name",
    section: "basic",
    validationRules: { minLength: 2, maxLength: 255 },
  },
  {
    entityType: "ev_station",
    fieldName: "street_address",
    fieldType: "text",
    isCritical: false,
    displayName: "Street Address",
    section: "location",
    validationRules: { minLength: 2, maxLength: 255 },
  },
  {
    entityType: "ev_station",
    fieldName: "city",
    fieldType: "text",
    isCritical: false,
    displayName: "City",
    section: "location",
  },
  {
    entityType: "ev_station",
    fieldName: "state",
    fieldType: "enum",
    isCritical: false,
    displayName: "State",
    section: "location",
    enumSource: "us_state",
  },
  {
    entityType: "ev_station",
    fieldName: "zip",
    fieldType: "text",
    isCritical: false,
    displayName: "ZIP Code",
    section: "location",
    validationRules: { pattern: "^\\d{5}(-\\d{4})?$" },
  },
  {
    entityType: "ev_station",
    fieldName: "latitude",
    fieldType: "float",
    isCritical: true,
    displayName: "Latitude",
    section: "location",
    precision: 6,
    minValue: -90,
    maxValue: 90,
    validationRules: { min: -90, max: 90 },
  },
  {
    entityType: "ev_station",
    fieldName: "longitude",
    fieldType: "float",
    isCritical: true,
    displayName: "Longitude",
    section: "location",
    precision: 6,
    minValue: -180,
    maxValue: 180,
    validationRules: { min: -180, max: 180 },
  },
  {
    entityType: "ev_station",
    fieldName: "ev_network",
    fieldType: "text",
    isCritical: false,
    displayName: "EV Network",
    section: "technical",
  },
  {
    entityType: "ev_station",
    fieldName: "ev_level1_evse_num",
    fieldType: "integer",
    isCritical: false,
    displayName: "Level 1 Chargers",
    section: "technical",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "ev_station",
    fieldName: "ev_level2_evse_num",
    fieldType: "integer",
    isCritical: false,
    displayName: "Level 2 Chargers",
    section: "technical",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "ev_station",
    fieldName: "ev_dc_fast_num",
    fieldType: "integer",
    isCritical: false,
    displayName: "DC Fast Chargers",
    section: "technical",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "ev_station",
    fieldName: "ev_pricing",
    fieldType: "text",
    isCritical: false,
    displayName: "EV Pricing",
    section: "technical",
  },
  {
    entityType: "ev_station",
    fieldName: "access_code",
    fieldType: "enum",
    isCritical: false,
    displayName: "Access Type",
    section: "basic",
    enumSource: "ev_access_code",
    validationRules: { enum: ["public", "private", "restricted"] },
  },
  {
    entityType: "ev_station",
    fieldName: "status_code",
    fieldType: "enum",
    isCritical: false,
    displayName: "Status",
    section: "basic",
    enumSource: "ev_status_code",
    validationRules: { enum: ["E", "P", "T"] },
  },

  // === PRICING NODES ===
  {
    entityType: "pricing_node",
    fieldName: "name",
    fieldType: "text",
    isCritical: true,
    displayName: "Node Name",
    section: "basic",
    validationRules: { minLength: 2, maxLength: 255 },
  },
  {
    entityType: "pricing_node",
    fieldName: "node_type",
    fieldType: "enum",
    isCritical: true,
    displayName: "Node Type",
    section: "basic",
    enumSource: "pricing_node_type",
  },
  {
    entityType: "pricing_node",
    fieldName: "state",
    fieldType: "enum",
    isCritical: false,
    displayName: "State",
    section: "location",
    enumSource: "us_state",
  },
  {
    entityType: "pricing_node",
    fieldName: "latitude",
    fieldType: "float",
    isCritical: true,
    displayName: "Latitude",
    section: "location",
    precision: 6,
    minValue: -90,
    maxValue: 90,
    validationRules: { min: -90, max: 90 },
  },
  {
    entityType: "pricing_node",
    fieldName: "longitude",
    fieldType: "float",
    isCritical: true,
    displayName: "Longitude",
    section: "location",
    precision: 6,
    minValue: -180,
    maxValue: 180,
    validationRules: { min: -180, max: 180 },
  },
  {
    entityType: "pricing_node",
    fieldName: "voltage_kv",
    fieldType: "float",
    isCritical: false,
    displayName: "Voltage",
    section: "technical",
    precision: 2,
    unit: "kV",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "pricing_node",
    fieldName: "zone",
    fieldType: "text",
    isCritical: false,
    displayName: "Zone",
    section: "technical",
  },

  // === PROGRAMS ===
  {
    entityType: "program",
    fieldName: "name",
    fieldType: "text",
    isCritical: true,
    displayName: "Program Name",
    section: "basic",
    validationRules: { minLength: 2, maxLength: 255 },
  },
  {
    entityType: "program",
    fieldName: "description",
    fieldType: "text",
    isCritical: false,
    displayName: "Description",
    section: "basic",
    validationRules: { maxLength: 5000 },
  },
  {
    entityType: "program",
    fieldName: "capacity_target",
    fieldType: "float",
    isCritical: false,
    displayName: "Capacity Target",
    section: "metrics",
    precision: 2,
    unit: "MW",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "program",
    fieldName: "max_enrollments",
    fieldType: "integer",
    isCritical: false,
    displayName: "Max Enrollments",
    section: "metrics",
    minValue: 0,
    validationRules: { min: 0 },
  },
  {
    entityType: "program",
    fieldName: "launched_at",
    fieldType: "text",
    isCritical: false,
    displayName: "Launch Date",
    section: "dates",
  },
  {
    entityType: "program",
    fieldName: "enrollment_opens",
    fieldType: "text",
    isCritical: false,
    displayName: "Enrollment Opens",
    section: "dates",
  },
  {
    entityType: "program",
    fieldName: "enrollment_closes",
    fieldType: "text",
    isCritical: false,
    displayName: "Enrollment Closes",
    section: "dates",
  },
  {
    entityType: "program",
    fieldName: "ends_at",
    fieldType: "text",
    isCritical: false,
    displayName: "End Date",
    section: "dates",
  },
  {
    entityType: "program",
    fieldName: "status",
    fieldType: "enum",
    isCritical: true,
    displayName: "Status",
    section: "basic",
    enumSource: "program_status",
    validationRules: {
      enum: ["DRAFT", "ACTIVE", "PAUSED", "FULL", "ARCHIVED"],
    },
  },
  {
    entityType: "program",
    fieldName: "program_website",
    fieldType: "url",
    isCritical: false,
    displayName: "Program Website",
    section: "contact",
  },
  {
    entityType: "program",
    fieldName: "faq_url",
    fieldType: "url",
    isCritical: false,
    displayName: "FAQ URL",
    section: "contact",
  },
  {
    entityType: "program",
    fieldName: "terms_url",
    fieldType: "url",
    isCritical: false,
    displayName: "Terms URL",
    section: "contact",
  },
  {
    entityType: "program",
    fieldName: "contact_url",
    fieldType: "url",
    isCritical: false,
    displayName: "Contact URL",
    section: "contact",
  },
  // Multi-value enum arrays (JSONB). Options are sourced from the canonical
  // enums in types/programs.ts so the registered option list cannot drift from
  // the values the app writes (see enum-subset test + CIR-1506).
  {
    entityType: "program",
    fieldName: "asset_types",
    fieldType: "multi_enum",
    isCritical: true,
    displayName: "Asset Types",
    section: "attributes",
    enumSource: "asset_type",
    validationRules: { enum: Object.values(AssetType) },
  },
  {
    entityType: "program",
    fieldName: "market_segments",
    fieldType: "multi_enum",
    isCritical: false,
    displayName: "Market Segments",
    section: "attributes",
    enumSource: "market_segment",
    validationRules: { enum: Object.values(MarketSegment) },
  },
  {
    entityType: "program",
    fieldName: "grid_services",
    fieldType: "multi_enum",
    isCritical: true,
    displayName: "Grid Services",
    section: "attributes",
    enumSource: "grid_service",
    validationRules: { enum: Object.values(GridService) },
  },
  {
    entityType: "program",
    fieldName: "participation_models",
    fieldType: "multi_enum",
    isCritical: false,
    displayName: "Participation",
    section: "attributes",
    enumSource: "participation_model",
    validationRules: { enum: Object.values(ParticipationModel) },
  },
  {
    entityType: "program",
    fieldName: "incentive_structures",
    fieldType: "multi_enum",
    isCritical: false,
    displayName: "Incentive Structures",
    section: "attributes",
    enumSource: "incentive_structure",
    validationRules: { enum: Object.values(IncentiveStructure) },
  },
];

async function seedEditableFields() {
  console.log("🌱 Seeding community_editable_fields...");

  // Clear existing data
  await db.execute(sql`DELETE FROM community_editable_fields`);
  console.log("   Cleared existing field definitions");

  // Insert all field definitions
  for (const field of fields) {
    await db.insert(communityEditableFields).values({
      entityType: field.entityType,
      fieldName: field.fieldName,
      fieldType: field.fieldType,
      isCritical: field.isCritical,
      displayName: field.displayName,
      validationRules: field.validationRules || null,
    });
  }

  console.log(`   Inserted ${fields.length} field definitions`);
  console.log("✅ Seed complete");
}

seedEditableFields()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  });
